version: "3.8"
services:
    nodeserver:
        build:
            context: ./Server
        ports:
            - "8080:8080"
    nginx:
        restart: always
        build:
            context: ./Server/nginx
        ports:
            - 8000:80
            - 5000:443
    reactserver:
        build:
            context: ./UI
        ports:
            - 80:80
            - 443:443
